name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build API image
        run: docker build -t portfolio_api:latest -f apps/api/Dockerfile .

      - name: Build Web image
        run: docker build -t portfolio_web:latest -f apps/web/Dockerfile --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} --build-arg NEXT_PUBLIC_API_URL_ORIGIN=${{ secrets.NEXT_PUBLIC_API_URL_ORIGIN }} --build-arg NEXT_PUBLIC_CLARITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLARITY_PROJECT_ID }} --build-arg NEXT_PUBLIC_CALENDLY_URL=${{ secrets.NEXT_PUBLIC_CALENDLY_URL }} --build-arg NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }} .

      - name: Deploy
        run: docker compose -f /apps/portfolio/compose.yml up -d --no-build
